name = "LDrawParser"
uuid = "c9062c12-fdd7-47de-ae43-3b8a76d3a662"
authors = ["kylebrown <kylejbrown17@gmail.com> and contributors"]
version = "0.1.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
