name = "LDrawParser"
uuid = "c9062c12-fdd7-47de-ae43-3b8a76d3a662"
authors = ["kylebrown <kylejbrown17@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GraphUtils = "5d4bc1c0-0fb7-11e9-3252-b1aa07358cab"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Rotations = "1.0"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
